version: "3.3"

services:
  app:
    container_name: app-chocolate-api
    env_file: .env
    build: .
    volumes:
      - ".:/usr/app"
      - /usr/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
  db:
    image: "mongo"
    container_name: chocolate-mongo-db
    ports:
      - 27017:27017
